#!/usr/bin/env sh

if [[ -x $(command -v python3) ]]; then
    python3 personal_finance.py $@
elif [[ -x $(command -v python) ]]; then
    python personal_finance.py $@
else
    echo "Python must be installed to use this CLI"
    exit 126
fi
